# NumPy crash overview

In [210]:
import numpy as np

In [211]:
np.__version__


'1.26.4'

## Array ceration

In [212]:
a = np.array([1,2,3,4,5,6]) # creat array in this way
print(a)

[1 2 3 4 5 6]


In [213]:
b = [1,2,3,4,5,6] # first creat list
b

[1, 2, 3, 4, 5, 6]

In [214]:
type(b)

list

In [215]:
b = np.array(b) # change its type to array

In [216]:
b

array([1, 2, 3, 4, 5, 6])

In [217]:
type(b)

numpy.ndarray

### arange()
  - To print sequence of thw number use arange

In [218]:
np.arange(10) # as argu. as 10 it print 0 to 9 in output 10 inexcluded

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [219]:
np.arange(9.7) # it print decimal value from 1.0 to 9.0 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [220]:
np.arange(1,10) # here first argu. act as first / starting index and 2nd argu act as end of the index so no. should print 1 to 9 , 10 is exclude.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [221]:
np.arange(-9,12)

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11])

In [222]:
np.arange(23,2) # it not able to print the numbeer sequence bcz there should be end index is greater then the start index

array([], dtype=int32)

In [223]:
np.arange(1,20,3) # here 1st and 2nd argu. work as it is and the 3rd index work as step to print the sequence , here like 1,4,7 etc.

array([ 1,  4,  7, 10, 13, 16, 19])

In [224]:
np.arange(-3,10,2)

array([-3, -1,  1,  3,  5,  7,  9])

In [225]:
np.arange(0,10,2,2) # the arrange function only take 3  argu. not more

TypeError: Cannot interpret '2' as a data type

### zeros() attribute
  - it return 0 

In [226]:
np.zeros(10) # print zero(0) in a list by defult is float type

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [227]:
np.zeros(10,dtype=int) # to change data type we have to change its dtype to int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [228]:
np.zeros((3,4),dtype=int) # to print the zeros in matrix format


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### one() attribute
   - it return 1

In [229]:
np.ones(6) # print ones in a row format by defult its float 
           # its called parameter tuning means system defult value

array([1., 1., 1., 1., 1., 1.])

In [230]:
np.ones(7,dtype=int) # to chnge to int datatype
                    # if user change as per use the its called hyper parameter tuning

array([1, 1, 1, 1, 1, 1, 1])

In [231]:
np.ones((3,5),dtype=int) # to print one in to matrix format

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [232]:
np.tows(4) # numpy only have ones and zeros attribute

AttributeError: module 'numpy' has no attribute 'tows'

### range() attribute
   - generate sequence of number

In [233]:
np.range(8)

AttributeError: module 'numpy' has no attribute 'range'

In [234]:
from numpy import* # it help to import all the function nd atribute 

In [235]:
range(4)

range(0, 4)

In [236]:
list(range(4)) # to print range

[0, 1, 2, 3]

In [237]:
zeros(5) # we can print this way also

array([0., 0., 0., 0., 0.])

## random.rand() ### --> use to generate random number decimal value

In [238]:
a = np.random.rand(9) # it help to generate randon value 
a

array([0.19768925, 0.54615219, 0.65395948, 0.02640258, 0.49330635,
       0.21026219, 0.73229413, 0.82866594, 0.74957233])

In [239]:
np.random.rand(9)*100 # to get 2 desimal point

array([ 8.41277122, 13.94552159, 11.02717587,  2.45095654, 34.9012508 ,
       37.69930051, 77.32712645, 44.06177215, 89.781631  ])

In [240]:
np.round(np.random.rand(7)*100) # to get round value of desimal value

array([56.,  0., 67., 33., 48., 94., 33.])

## random.randint() --> use to generate random integer number

In [241]:
a = np.random.randint(7) #to generate rendom integer value till 7
a

3

In [242]:
np.random.randint(5,9) # to generate random integer value from 5 to 9

8

In [243]:
np.random.randint(2,8,6) # here number are generate in beween 2 to 8 and 6 number should be generated

array([2, 3, 4, 3, 7, 7])

In [244]:
np.random.randint(2,7,(5,5)) # number are generated from 2 to 7 and in the matrix form of 5 x 5 or 25 elements

array([[5, 5, 6, 2, 6],
       [6, 3, 2, 6, 5],
       [5, 2, 4, 5, 2],
       [2, 4, 4, 4, 6],
       [2, 4, 3, 5, 4]])

## Array slicing 

In [245]:
a = np.random.randint(0,50,(8,8)) # number of matrix is generate from 0 to 50 with 8 x 8 marix
print(a)

[[49 27 15 23 33 21 21 23]
 [42 42 40  7 30  9 38 15]
 [36 48 27 17 45 30 43 33]
 [27 45 23 48 46  1 17 15]
 [26 48  8 45 34 36 22  2]
 [42 11 44 25 17 10 19  2]
 [45  7 29 32 12 46 17 12]
 [42 44 37 35 25 21 38 19]]


In [246]:
a

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [247]:
a[:] # print all the matrix value

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [248]:
a[3:] # print the matrix 3rd indexrowto the end rows

array([[27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [249]:
a[:4] # print the matrix from 0 th index to (4-1)th index

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15]])

In [250]:
a[0:-1] # it also print till -2 index rows value of the matrix

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12]])

In [251]:
a

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [252]:
a[2:-1] # it print from 2ndindex row to -1 index colums all values

array([[36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12]])

In [253]:
a[-4:-1] # print -4 index rows with -1 index column values

array([[26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12]])

In [254]:
a[3,6] # it gives the individual value from combination of 3rd index row and 6th index column

17

In [255]:
a[2,-4] # it gives value 2ndindes row and -4 index value combination

45

In [256]:
a[-4,-3] # combination of -4 index rows and -3 index columns

36

In [257]:
a[::] # print all the matrix value

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [258]:
a[::-1] # it help to reverse the metrix row last row comes to first andso on

array([[42, 44, 37, 35, 25, 21, 38, 19],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [49, 27, 15, 23, 33, 21, 21, 23]])

In [259]:
a[::-2] # it print from the last -2 indexingformat

array([[42, 44, 37, 35, 25, 21, 38, 19],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [42, 42, 40,  7, 30,  9, 38, 15]])

## Array operation

In [260]:
a

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [261]:
a.sum() # itgive sum of all the elements

1788

In [262]:
a.mean() # its calculate the average of the matrix value

27.9375

In [263]:
a.max() # it find the maximum value inthe matrix

49

In [264]:
a

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [265]:
a.min() # it calculate minimum value of the matrix

1

In [266]:
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

#### To get median function we have  to do the following

In [267]:
from numpy import*
a

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [268]:
median(a)

27.0

### reshape() attribute
 - to give reshape to the array elements

In [269]:
b = np.random.randint(0,100,12) # generate 12 random number from 0 to 100

In [270]:
b

array([76, 25, 71, 37, 87, 48, 45, 43, 41, 21, 90, 12])

In [271]:
b

array([76, 25, 71, 37, 87, 48, 45, 43, 41, 21, 90, 12])

In [272]:
b.reshape(4,3) # it arange the number in to a 4 x 3 matrix value


array([[76, 25, 71],
       [37, 87, 48],
       [45, 43, 41],
       [21, 90, 12]])

In [273]:
b.reshape(2,6) # it arange in to 2 x 6 matrix. N.B - reshape work when the total number is to be reshape is same with multiplication of reshape argu. 

array([[76, 25, 71, 37, 87, 48],
       [45, 43, 41, 21, 90, 12]])

In [274]:
c = np.array([1,2,3,4,5,6])
c

array([1, 2, 3, 4, 5, 6])

In [275]:
c.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [276]:
c.reshape(2,3,order='c') # order represent how the data will print here dta print in 'C' format

array([[1, 2, 3],
       [4, 5, 6]])

In [277]:
c.reshape(2,3,order='f') # here data are print in fortran format

array([[1, 3, 5],
       [2, 4, 6]])

In [278]:
c.reshape(2,3,order='a') # here data are print in arbitrary / defult c type

array([[1, 2, 3],
       [4, 5, 6]])

In [279]:
c

array([1, 2, 3, 4, 5, 6])

In [280]:
c.reshape(4,2) # it show error becz 4*2 = 8, but only 6 value have to print, if the value no. are 8 then it work properly

ValueError: cannot reshape array of size 6 into shape (4,2)

### Array slicing concept that left

In [281]:
a

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [282]:
a[3,:] # to get only one row as out put

array([27, 45, 23, 48, 46,  1, 17, 15])

In [283]:
a[:,4] # to get only one column as out put

array([33, 30, 45, 46, 34, 17, 12, 25])

In [284]:
a[0:5] # print values of all 5 columns

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2]])

In [285]:
a[:,-1] # to get last columns only

array([23, 15, 33, 15,  2,  2, 12, 19])

In [286]:
a[-1,:] # to get last rows only

array([42, 44, 37, 35, 25, 21, 38, 19])

In [287]:
a[4:] # it print from 4th index rowto till last


array([[26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [288]:
a

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [289]:
a[0:8:2] # step countprint 

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [45,  7, 29, 32, 12, 46, 17, 12]])

In [290]:
a

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [291]:
a[0,6] # use comma to get specific value

21

In [292]:
a[0:6] # use colon to gate the array values

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2]])

In [293]:
a

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [294]:
a[1:5,2:5] # 1:5 indicate row part , 2:5indicate column part

array([[40,  7, 30],
       [27, 17, 45],
       [23, 48, 46],
       [ 8, 45, 34]])

In [295]:
a[2:3,2:3] # 2:3 indicate row part , 2:3 indicate column part


array([[27]])

In [296]:
id(a)

1686873063760

## Masking

In [297]:
b = np.arange(0,25).reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [298]:
b >10 # it give where the b value greater that 10return true otherwise false

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [299]:
a

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [300]:
a < 20 # it give where the a value less that 20 return true otherwise false

array([[False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False,  True, False,  True],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False,  True,  True,  True],
       [False, False,  True, False, False, False, False,  True],
       [False,  True, False, False,  True,  True,  True,  True],
       [False,  True, False, False,  True, False,  True,  True],
       [False, False, False, False, False, False, False,  True]])

In [301]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [302]:
b ==14 # where the value of 14 is available it return true else false

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [303]:
b >= 15 # value including 15 greater value return true else false


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [304]:
a

array([[49, 27, 15, 23, 33, 21, 21, 23],
       [42, 42, 40,  7, 30,  9, 38, 15],
       [36, 48, 27, 17, 45, 30, 43, 33],
       [27, 45, 23, 48, 46,  1, 17, 15],
       [26, 48,  8, 45, 34, 36, 22,  2],
       [42, 11, 44, 25, 17, 10, 19,  2],
       [45,  7, 29, 32, 12, 46, 17, 12],
       [42, 44, 37, 35, 25, 21, 38, 19]])

In [305]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [306]:
b[b == 8] # it print the value is equal to 8

array([8])

In [307]:
b[ b > 8] # it print the value from greater to 8

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [308]:
b[b >= 8] # including 8 and avobe value are print

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [309]:
b[b == 90] # if valuenot in the array it return empty value

array([], dtype=int32)

## 

## Basic Numpy complete