# NumPy Library¶
  - NumPy is a python Library which help to do operation on multidimentional array
  - Using NumPy we do fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discret Fourier transforms, basic line r algebra, basic statistical operations, random simulati etc.
  - NumPy is a ndarry(n-dimentional array) Object
  - The data must be in homogenious on

In [1]:
import numpy as np # Syntax to import the numpy library np stands for numpy

In [2]:
np.__version__ #check the version of NumPy

'1.26.4'

# Array are Three Type
  - 1D array -->[1,2,3,4] (value store in a one direction)
  - 2D array -->( value are store in two rows and two columns format)
  - nD array / multidimentional --> Data are store in multiple rows and columns formatmat

In [3]:
np.array([1,2,3,4,5]) # 1D array declaration

array([1, 2, 3, 4, 5])

In [4]:
arr = np.array([3,5,6,7,8,78])
print(arr)


[ 3  5  6  7  8 78]


In [5]:
arra1 = np.array([[2,4,6,8],[5,7,8,9]]) # 2D array declaration
arra1

array([[2, 4, 6, 8],
       [5, 7, 8, 9]])

In [6]:
arra2 = np.array([[23,56,67,87],[90,78,7,8],[65,4,3,8],[8,7,8,56],[44,21,43,65],[9,789,77,32]]) # N-D array declaration
print(arra2)

[[ 23  56  67  87]
 [ 90  78   7   8]
 [ 65   4   3   8]
 [  8   7   8  56]
 [ 44  21  43  65]
 [  9 789  77  32]]


In [7]:
arra3 = np.array([[23,56,67,87],[90,78,7,8],[65,4,3,8],[8,7,8,56],[44,21,43,65],[9,789,77,32]],dtype=float) # N-D array declaration of float type
print(arra3)

[[ 23.  56.  67.  87.]
 [ 90.  78.   7.   8.]
 [ 65.   4.   3.   8.]
 [  8.   7.   8.  56.]
 [ 44.  21.  43.  65.]
 [  9. 789.  77.  32.]]


In [8]:
array = np.array([56,0,34,78],dtype=bool) # array element with boolean data type
print(array)

[ True False  True  True]


In [9]:
array = np.array([[78,8,3,5,6],[5,1,6+7,6,8]], dtype=complex) # array element with complex data type
print(array)

[[78.+0.j  8.+0.j  3.+0.j  5.+0.j  6.+0.j]
 [ 5.+0.j  1.+0.j 13.+0.j  6.+0.j  8.+0.j]]


### Numpy Vs Python
  - NumPy array are fixed size but Python list are growable
  - if want to creat nd array then creat new one delete orginal one that exist
  - The element of NumPy array are same type but in Python its not
  - NumPy array element allow to do advance ,athematical operation on array of large number of data its very easy compair to Python operation
    

## Some built-in Function in Numpy library
   - arange(), reshape(), zeros(),ones(),linspace()

In [10]:
a = np.arange(12) # when we pass one arguments to arange function it consider 0 as strating index and go for (n-1) till value print sequence
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
b = np.arange(2,9) # when we pass two argument it take first argu. as starting index and second value as ending index and print the sequence
print(b)

[2 3 4 5 6 7 8]


In [12]:
c = np.arange(3,20,2) # when we pass 3 argumnet the first argu. as starting value, 2nd argu. as ending value and 3rd argu. as step value
print(c)

[ 3  5  7  9 11 13 15 17 19]


In [13]:
d = np.arange(1,8,2,3) # when we pass three argu. then its got error bcz arange function at most take three argu. not more
print(d)

TypeError: Cannot interpret '3' as a data type

In [ ]:
a = np.arange(1,13).reshape(4,3)# it print the element 1 to 12, with 4 rows and 3 columns, N.B-arange number(12) == reshape multiplication value(4*3=12)
print(a)

In [14]:
np.arange(1,13).reshape(2,6) # arenge 12 number = reshape (2*6=12)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [15]:
np.zeros(5) # print only zero(0) = number of argu. by defult its float

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros(7,dtype=int) # turn the zero data type float to integer

array([0, 0, 0, 0, 0, 0, 0])

In [17]:
np.zeros((3,4)) # print zeros(0) in nd array with float zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros((2,5),dtype=int) # turn these zero into integer data type in nd array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
np.zeros((5,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [20]:
b = np.ones(5) # ones() function give the array with values one, by defult its float datatype
print(b)

[1. 1. 1. 1. 1.]


In [21]:
np.ones(6,dtype=int) # to change the float data to integer data we have to change data type to int 

array([1, 1, 1, 1, 1, 1])

In [22]:
np.ones((2,4),dtype=int) # the first argu. is taken as rows number and 2nd argu. taken as column number where the valus of once are filled with

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
a = np.ones((3,6),dtype=int)
print(a)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [24]:
np.linspace(2,30,20) # linspace function use to number where start 1st argu. and end 2nd argu., 3rd argu. is the to no. of o/p

array([ 2.        ,  3.47368421,  4.94736842,  6.42105263,  7.89473684,
        9.36842105, 10.84210526, 12.31578947, 13.78947368, 15.26315789,
       16.73684211, 18.21052632, 19.68421053, 21.15789474, 22.63157895,
       24.10526316, 25.57894737, 27.05263158, 28.52631579, 30.        ])

In [25]:
np.linspace(-2,12,6) # in this function number to be generate is 6, starting value is -2, end value is 12, expecting the 12 there is 5 value
                    # rest value to print is 5 so (12-(-2)=14), the difference between teo no. should be 14/5(as last value already given) = 2.8
                    # it print the value from -2 to 20 with 2.8 interval

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

# Identity matrix
   - the diagonal values are one only others are zeros

In [26]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.identity(4,dtype=int) # it generate 5 X 5 matrix with integer type

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

## ndim atribute ---> to find the array dimentional value wheather it 1d, 2D or nd

In [28]:
a

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [29]:
a.ndim # as the array in 2 dimentional

2

In [30]:
arr

array([ 3,  5,  6,  7,  8, 78])

In [31]:
arr.ndim # the aray is one dimention

1

In [32]:
arra = np.arange(8,dtype=int).reshape(2,2,2) # 3 D array
arra

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [33]:
arra.ndim # it gives 3D array

3

## shape() 
    - this attribute gives what is the number of rows and columns by taking argu. as array name

In [34]:
np.shape(a) # a array is 3 rows and 6 columns

(3, 6)

In [35]:
np.shape(arr) # arr array have 6 column

(6,)

In [36]:
np.shape(arra) # arra array have 2 rows, 2 column, and 2 dimentions

(2, 2, 2)

### Size() 
   - This attribute give the the size of array or total number of items array has

In [37]:
a

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [38]:
np.size(a) # the array have 18 elements on it

18

In [39]:
arr

array([ 3,  5,  6,  7,  8, 78])

In [40]:
np.size(arr)

6

In [41]:
arra

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [42]:
np.size(arra)

8

In [43]:
arra.size # we can write in this format to print the size of the array

8

### itemsize attriute

In [44]:
a

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [45]:
a.itemsize # as the values are integer32 the it one item size to 4byte data to store

4

In [46]:
 b

array([1., 1., 1., 1., 1.])

In [47]:
b.itemsize # as the values are float64 the it one item size to 8 byte data to store

8

## dtype 
 - it gives the data type ofthe array
 - syntax- array_name.dtype

In [48]:
a.dtype

dtype('int32')

In [49]:
b.dtype

dtype('float64')

In [50]:
arra.dtype

dtype('int32')

In [51]:
arr.dtype

dtype('int32')

## Change Data type
  ### astype(int,float)
        - It help to chage the data type from exitng data type

In [52]:
a

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [53]:
a.astype(float) # it change the data type of array integer to float

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [54]:
b

array([1., 1., 1., 1., 1.])

In [55]:
b.astype(int) # float to intiger data type change

array([1, 1, 1, 1, 1])

## Array operation 

### Addition

In [56]:
a

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [57]:
a=a+3 # add 3 in avvery elements of the array its
print(a)

[[4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]]


In [58]:
arr

array([ 3,  5,  6,  7,  8, 78])

In [59]:
arr + 0.8

array([ 3.8,  5.8,  6.8,  7.8,  8.8, 78.8])

### Subtraction

In [60]:
a

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [61]:
a=a-3 # subtraction
print(a)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [62]:
b

array([1., 1., 1., 1., 1.])

In [63]:
arr

array([ 3,  5,  6,  7,  8, 78])

In [64]:
arr-2

array([ 1,  3,  4,  5,  6, 76])

### Multiplication

In [65]:
arr

array([ 3,  5,  6,  7,  8, 78])

In [66]:
arr*4 # multiply 4 in every element

array([ 12,  20,  24,  28,  32, 312])

In [67]:
arra

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [68]:
arra*2 # multiply 2 

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]]])

In [69]:
a1=np.array([[1,2,3,4],[5,6,7,8]])
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [70]:
a1*2 # multiply 2 in a1 array

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

### Division

In [71]:
a1/2 # devide 2 in a1 array

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [72]:
a

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [73]:
a/3

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.33333333]])

### modul

In [74]:
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
a1%2 # it give the module value

array([[1, 0, 1, 0],
       [1, 0, 1, 0]], dtype=int32)

In [76]:
arr

array([ 3,  5,  6,  7,  8, 78])

In [77]:
arr%3

array([0, 2, 0, 1, 2, 0], dtype=int32)

### Power

In [78]:
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
a1**3 # it give the power of every element of the  array

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

In [80]:
a

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [81]:
a**2

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [82]:
arr

array([ 3,  5,  6,  7,  8, 78])

In [83]:
arr**4

array([      81,      625,     1296,     2401,     4096, 37015056],
      dtype=int32)

## Relational operatior

In [84]:
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
a1<4 # a1 each value compair with 4 which get true return true other wise retun fulse

array([[ True,  True,  True, False],
       [False, False, False, False]])

In [86]:
a1>=4 # it return true if the valye is greater then 4 else false

array([[False, False, False,  True],
       [ True,  True,  True,  True]])

In [87]:
a1 ==5 # it return true where the value is 5 else false

array([[False, False, False, False],
       [ True, False, False, False]])

In [88]:
a1 != 2 # it false where 2 is exit other wise true

array([[ True, False,  True,  True],
       [ True,  True,  True,  True]])

## Vector operation

In [89]:
z = np.array([[1,2,3,4,5,],[1,2,3,4,5]])
print(z)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [90]:
z1 =np.array([[1,2,3,4,5,],[1,2,3,4,5]])
print(z1)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [91]:
z+z1 # both array size should be same to add each item accordingly

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10]])

In [92]:
z - z1 # both array size should be same to subtract with each item accordingly

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [93]:
z*z1 # both array size should be same to multiply each item accordingly

array([[ 1,  4,  9, 16, 25],
       [ 1,  4,  9, 16, 25]])

In [94]:
z / z1 # both array size should be same to devide with each item accordingly

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Array function

In [95]:
k = np.random.random((3,3)) # Creat random array with 3 x 3 matrix
k = np.round(k*100) # its helps to round the value
print(k)

[[34. 17. 15.]
 [ 3. 70. 74.]
 [21. 26. 24.]]


In [96]:
np.max(k) # gives the maximum number in the array

74.0

In [97]:
np.min(k) # It gives the minimum number in the array is present

3.0

In [98]:
np.average(k) # It calculate the average of all the elements are present in the array

31.555555555555557

In [99]:
np.sum(k) # It gives the sum of all the elements presenat in the array


284.0

In [100]:
np.prod(k) # Return The product of all array elements

1765525507200.0

In [101]:
np.max(k,axis=1) # it gives the maximum value in every rows individually

array([34., 74., 26.])

In [102]:
k

array([[34., 17., 15.],
       [ 3., 70., 74.],
       [21., 26., 24.]])

In [103]:
np.max(k,axis=0) # it gives the maximum value in every column individually

array([34., 70., 74.])

In [104]:
np.prod(k,axis=1) # it gives the product of every rows individually

array([ 8670., 15540., 13104.])

In [105]:
np.prod(k,axis=0) # it gives the product of every column individually

array([ 2142., 30940., 26640.])

### Statistical function

In [106]:
np.mean(k) # it give the mean value of the array

31.555555555555557

In [107]:
np.mean(k,axis=1) # mean by individual rows

array([22.        , 49.        , 23.66666667])

In [108]:
np.mean(k,axis=0) # mean by individual column

array([19.33333333, 37.66666667, 37.66666667])

In [109]:
np.median(k) # it give the median value of the array

24.0

In [110]:
np.median(k,axis=1) # median by individual rows

array([17., 70., 24.])

In [111]:
np.median(k,axis=0) # median by individual columns

array([21., 26., 24.])

In [112]:
np.std(k) # calculate the standard deviation of an array

23.060842767249476

In [113]:
np.std(k,axis=1) # standard deviation by individual rows

array([ 8.52447457, 32.56787783,  2.05480467])

In [114]:
np.std(k,axis=0) # standard deviation by individual columns

array([12.71045064, 23.15647258, 25.95294888])

In [115]:
np.var(k) # calculate variance of the array

531.8024691358024

In [116]:
np.var(k,axis=1) # variance by individual rows

array([  72.66666667, 1060.66666667,    4.22222222])

In [117]:
np.var(k,axis=0) # variance  by individual columns

array([161.55555556, 536.22222222, 673.55555556])

### Trigonometry Function 

In [118]:
k

array([[34., 17., 15.],
       [ 3., 70., 74.],
       [21., 26., 24.]])

In [119]:
np.sin(k) # it calculate sin of every value in the array

array([[ 0.52908269, -0.96139749,  0.65028784],
       [ 0.14112001,  0.77389068, -0.98514626],
       [ 0.83665564,  0.76255845, -0.90557836]])

In [120]:
np.cos(k) # it calculate cos of every value of array 

array([[-0.84857027, -0.27516334, -0.75968791],
       [-0.9899925 ,  0.6333192 ,  0.17171734],
       [-0.54772926,  0.64691932,  0.42417901]])

In [121]:
np.tan(k) # it calculate tan of every value of the array

array([[-0.62349896,  3.49391565, -0.8559934 ],
       [-0.14254654,  1.22195992, -5.73702254],
       [-1.52749853,  1.17875355, -2.1348967 ]])

In [122]:
np.sec(k) # the numpy have only trigonomerty attribute sin(),cos(),and tan()

AttributeError: module 'numpy' has no attribute 'sec'

### dot product attribute

In [123]:
m = np.arange(12,24).reshape(4,3)
m

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [124]:
n = np.arange(0,12).reshape(3,4)
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
np.dot(m,n) # dot product of m and n

array([[164, 203, 242, 281],
       [200, 248, 296, 344],
       [236, 293, 350, 407],
       [272, 338, 404, 470]])

### log and exponential

In [126]:
np.exp(k) # it gives the exponential value of the array

array([[5.83461743e+14, 2.41549528e+07, 3.26901737e+06],
       [2.00855369e+01, 2.51543867e+30, 1.37338298e+32],
       [1.31881573e+09, 1.95729609e+11, 2.64891221e+10]])

In [127]:
np.log(k) # Logarithm value of the array


array([[3.52636052, 2.83321334, 2.7080502 ],
       [1.09861229, 4.24849524, 4.30406509],
       [3.04452244, 3.25809654, 3.17805383]])

## Round 
  - in NumPy library round() function use to round off the value with the near integer value

In [128]:
m = np.array([1.5,4.55,6.7,8.9,56.6,78])
m

array([ 1.5 ,  4.55,  6.7 ,  8.9 , 56.6 , 78.  ])

In [129]:
np.round(m) # round of the elemnent in the array with the nearest integer value

array([ 2.,  5.,  7.,  9., 57., 78.])

In [130]:
 n = np.array([1.2344,3.4535,4.5567,8.9909,56.77667])
n

array([ 1.2344 ,  3.4535 ,  4.5567 ,  8.9909 , 56.77667])

In [131]:
np.round(n,decimals=3) # it take 3 decimal value to roundup with near intiger value

array([ 1.234,  3.454,  4.557,  8.991, 56.777])

In [132]:
a =np.random.random((3,4))*100
a

array([[14.01239517,  5.60799614, 99.84973262, 30.22212408],
       [27.41152426, 75.40008797, 67.99627406, 35.65468496],
       [51.74954144, 90.98847497, 77.74134069, 68.00169524]])

In [133]:
np.round(a)

array([[ 14.,   6., 100.,  30.],
       [ 27.,  75.,  68.,  36.],
       [ 52.,  91.,  78.,  68.]])

In [134]:
np.round(np.random.random((3,4))*100)  # above two line combine into one line

array([[91.,  9., 11., 35.],
       [71., 46., 84., 52.],
       [60., 14., 63., 59.]])

## Floor
   - in NumPy library floor() function use to find the integer value from the float value
   - ex- 3.78668 is turned as 3

In [135]:
 a = np.array([12.4454,3.5,66.7,45.87,67.9997])
a

array([12.4454,  3.5   , 66.7   , 45.87  , 67.9997])

In [136]:
np.floor(a) # It ruturn the integer velue of the all array float value

array([12.,  3., 66., 45., 67.])

In [137]:
np.floor(np.random.random((3,5))*100) # to generate random number with floor

array([[64., 57., 31., 44., 60.],
       [ 7., 43., 81., 88., 28.],
       [11., 10., 35.,  9., 21.]])

## ceil
   - it give in output as highest integer value
   - ex 2.3 = 3, 3.7 = 4 , 9.0 = 9

In [138]:
a = np.array([1.2,3.4,3.5,5.6,7.8,9.0])
a

array([1.2, 3.4, 3.5, 5.6, 7.8, 9. ])

In [139]:
np.ceil(a) # it give highest integer value or equal value (9.0 = 9)

array([2., 4., 4., 6., 8., 9.])

In [140]:
b = np.random.random((2,3))*100
b

array([[80.25423258, 16.68823872, 98.544642  ],
       [19.62089866, 38.70302549,  3.90854657]])

In [141]:
np.ceil(b)

array([[81., 17., 99.],
       [20., 39.,  4.]])

In [142]:
np.ceil(np.random.random((2,3))*100) # generate random value after combine above two line into one

array([[46., 83., 80.],
       [11., 22., 47.]])

## indeex slicing
  - 

In [143]:
a = np.random.randint(1,10,(5,5)) # generate random integer value from 1 to 10 with 5 x 5 matrix

In [144]:
a

array([[3, 7, 2, 1, 3],
       [5, 9, 6, 5, 1],
       [9, 8, 7, 6, 7],
       [7, 3, 4, 5, 8],
       [9, 2, 3, 5, 7]])

In [145]:
a[:] # to print all the element of the 2D array use these

array([[3, 7, 2, 1, 3],
       [5, 9, 6, 5, 1],
       [9, 8, 7, 6, 7],
       [7, 3, 4, 5, 8],
       [9, 2, 3, 5, 7]])

In [146]:
a[:-1] # also this is the format to print the element of array excepting lasr rows

array([[3, 7, 2, 1, 3],
       [5, 9, 6, 5, 1],
       [9, 8, 7, 6, 7],
       [7, 3, 4, 5, 8]])

In [147]:
a[1:3] # 1st argu. represent the starting index and 2nd argu represent 3rd iindex it print accordingly 

array([[5, 9, 6, 5, 1],
       [9, 8, 7, 6, 7]])

In [148]:
a

array([[3, 7, 2, 1, 3],
       [5, 9, 6, 5, 1],
       [9, 8, 7, 6, 7],
       [7, 3, 4, 5, 8],
       [9, 2, 3, 5, 7]])

In [149]:
a[-3:-1] 

array([[9, 8, 7, 6, 7],
       [7, 3, 4, 5, 8]])

In [150]:
a[1:3,2:3] # 1st 1:3 represnt to the rows and 2nd 2:3 represent the columns for calculations

array([[6],
       [7]])

In [151]:
b= np.arange(1,101).reshape(10,10)

In [152]:
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [153]:
b[0:10:2] # print start from 0th index end index is 10th and step to print the value is 2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [154]:
b[4] # printing only rows

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [155]:
b[4,:] # also this way we can print the rows

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [156]:
b[:,3] #printing only columns 

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [157]:
n1 = np.arange(1,9)
n2 = np.arange(1,13).reshape(4,3)
n3 = np.arange(1,28).reshape(3,3,3)

In [158]:
n1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [159]:
# our desire element is 6
n1[5]

6

In [160]:
# our desire element is 7
n1[-2]

7

In [161]:
np.sum(n1)

36

In [162]:
n2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [163]:
# desire element is 8 
n2[2,1]   # positive indexing

8

In [164]:
# desire element is 6
n2[-3,-1] # negative indexing

6

In [165]:
# desire element is 7 using positive and negaative indexing
n2[-2,0]

7

In [166]:
n3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [167]:
# desire element is 17
n3[1,2,1]


17

In [168]:
# desire element is 23
n3[2,1,1]

23

In [169]:
# desire element 27
n3[2,2,2] # 1st argu act as which matrix , 2nd argu as rows and 3rd argu as column

27

### slicing in 3D

In [170]:
n3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [171]:
n3[1] # it gives 2nd array of 2D bcz array index start from 0

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [172]:
n3[::2] # starting from 0 to last index with step 2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [173]:
n3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [174]:
# fetch 13,14,15
n3[1,1,:]

array([13, 14, 15])

In [175]:
# fatch 20,23,26
n3[2,:,1]

array([20, 23, 26])

## iterating array

In [176]:
n1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [177]:
n2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [178]:
n3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [180]:
for i in n1:
    print(i)

1
2
3
4
5
6
7
8


In [181]:
for i in n2:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [182]:
for i in n3:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


In [183]:
# print 2D  array element into a 1d array
for i in np.nditer(n2): # nd.nditer() help to print the array element of 2d and 3d element into a single ist
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [185]:
for i in np.nditer(n3): # print 3d array element into a single list
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [186]:
n2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [187]:
np.transpose(n2) # it print the transpose of the given matrix array means rows become columns and columns become rows

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [188]:
n2.T # it is an another method to print transpose of matrix

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

### ravel()
  - The ravel function help to change the 2d and 3d array in to 1d array

In [189]:
n2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [191]:
np.ravel(n2) # it generate the all element of the n2 array which is 2d return to 1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [192]:
n3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [193]:
np.ravel(n3) # it return the 3d array element into  1d array as return

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

## Stacking
   - Fpr stacking use hstack(),vstack() function
   - here stacking done in more than 2 array
   - here we can do two type of stacking hstack(), vstack()
   - hstack()--> add the matrix into horizontal manner
   - vstack()--> add the matrix into vertical manner

In [201]:
h = np.arange(1,13).reshape(4,3)
h1 = np.arange(13,25).reshape(4,3)


In [202]:
h

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [203]:
h1

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [205]:
np.hstack((h,h1)) # here hstack add the two array in horizontal manner


array([[ 1,  2,  3, 13, 14, 15],
       [ 4,  5,  6, 16, 17, 18],
       [ 7,  8,  9, 19, 20, 21],
       [10, 11, 12, 22, 23, 24]])

In [206]:
np.hstack((h1,h)) # change the array appearance

array([[13, 14, 15,  1,  2,  3],
       [16, 17, 18,  4,  5,  6],
       [19, 20, 21,  7,  8,  9],
       [22, 23, 24, 10, 11, 12]])

In [207]:
h

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [208]:
h1

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [210]:
np.vstack((h,h1)) # it add the array in to vertical manner

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

### N.B - if the matrix size it not work it show error, letd ex- one 3 x 4 and 4 x 3 can not able to add 

In [211]:
n = np.arange(0,10).reshape(2,5)
n1 = np.arange(10,20).reshape(5,2)
# the above two matrix are not same becz one is 5 x 2 and 2 x 5

In [212]:
n

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [213]:
n1

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [214]:
# lets do stacking

In [215]:
np.hstack((n,n1)) # it show error becaz matrix size are not same

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 5

In [216]:
np.vstack((n,n1)) # it also show error

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 2

## Speliting
  - it split the whole array into number of array
  - here we yse two types of spliting hsplit() and vsplit()
  - hsplit()--> split the array into horizontally
  - vsplit() --> split the array into vertically

In [217]:
n

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [221]:
np.hsplit(n,2) # it shows error becz the spliting should be in equal devision

ValueError: array split does not result in an equal division

In [222]:
# to get the out put
n

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [226]:
np.vsplit(n,2) # it split vertically the array

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

In [227]:
n1

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [229]:
np.hsplit(n1,2) # it split the aray into vertically

[array([[10],
        [12],
        [14],
        [16],
        [18]]),
 array([[11],
        [13],
        [15],
        [17],
        [19]])]

In [232]:
a = np.arange(1,37).reshape(6,6)

In [233]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [237]:
np.hsplit(a,2) #it split the whole array into 2 same shape array as we pass 2 so it creat two array

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21],
        [25, 26, 27],
        [31, 32, 33]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24],
        [28, 29, 30],
        [34, 35, 36]])]

In [238]:
np.hsplit(a,3) # it split into 3 array of same size

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]

In [239]:
np.vsplit(a,3) # it split array of same size vertically

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

## logical operation
  -  and(&) --> if all the conditions are true return true other wise false
  -  or(|)--> if all the condition are false return false othewise true
  -  not(~) --> it take one condition if it true return false and vise versa

In [242]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [249]:
(a>20) & (a%2==0) # it return the value true where the both given condition are true

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]])

In [251]:
(a>20) | (a%2==0) # if any one of the condition is true that pass then it return true

array([[False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [252]:
(a)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [256]:
~ (a>20) # it check which value is greater than 20 which is less then 20 and change accordingly false -> true and true-> false

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [257]:
a[~ (a>20)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])